Connection:
  Count: "______________ _8o&&0oo* . . . . . . . . . . . . . . . . . . . oooo&o&8*"
Hosts:
  IP: "_______________________ .8o&&ooo* . . . . . . . . . . . . . . . . . . (ooo&o&8*"
  Count: "_____________________ ..ohooo&&&&&&&&o&&o&&&&&oo:::::oo&&&&o&ooo&&&&&&&&&o8"
Machine:
  Cores: "_____________________ .hh&o&&&&&&o&ooo&o&&ooo&&&&oooo&&o&&ooo&&&&&&o&hh"
  Cpu: "________________________ _h8hh&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&hh"
  DiskSpace: "___________________ .|o&oo*o&&o&&&&&&&&&&&&&&&&&&&&&&&&&&oo&o&o&o"
  Memory: "_____________________ (oo& .. oo&&&&&&&&&&&&&&&&&&&&&&&&&&&&oo .. &oo"
  FreeDisk: "__________________  poo& .. oo&&&&&&&&&&&&&&&&&&&&&&&&&&&&oo .. &oo"
  FreeMem: "___________________ (o&& . 8@ .oo&o&&&&&&&&&&&&&&&&&&&&&o&o  8@ . o&&"
  NewProcesses: "_____________ (&oo . @@@@: .oo&oo&&&&&&&&&&&&&&&o&o&:. @@@@ . &o"
  LastConnecTime: "___________ (&&&. 8@@@@@ . *o&o&&&&&&&&&&&&&&&&&& . .@@@@@ .*o"
  Process: "__________________ (&o&. 8@@@@ . @ .o&&&&&&&&&&&&&&&o&. 8o. h@@@@ .*o"
  ProcIncoming: "______________ (ooo . h@@@@@@@@& *oo&&&&&&&&&&o  @@@@@@@@@ . &o"
  ProcInternal: "_______________ (ooo* . .o@@@@@@h .&oo&&&&&&&: h@@@@@@@ . . o&"
  ProcOutgoing: "________________ (oo&&. . . . . . .&oo&&&&o*. . . . . . ooo&"
  ProcConnectionCount: "___________ (&o&&&ooooo&* . oo&&&&/. .ooooooo&o&&."
  ProcSessionId: "______________________ (oooo&&&&&o&&&&&oo&o&&&oo&o."
User:
  DownloadedProcesses: "_____________________________ ..&&oo"
  File: "_____________________________________________ ..oo"
  Zone: "______________________________________________ .1"
Team:
  Name: "DYPC"
  Members: "Liya, Max & Elad"